### ISSUE TITLE
Put requests fail if any key has a value of null.

### ISSUE THREAD

**Issue by wescorn** [LasseRafn/laravel-economic#21]
I'm trying to do an update on a DraftInvoice, but if any of the model properties are null, the request fails.
 
Specifically, i used a TemplateInvoice to create a DraftInvoice, then added a few "lines" to the draftinvoice, and wanted to update it. But since the name, project and notes props of the DraftInvoice Model are null, i get an exception when i call the update method, basically stating that the value of the project prop is wrong (it is null). I assume it is because e-conomics api doesn't take null as a valid value.

So i'd suggest removing any null properties from the object, before sending the put request?

**Comment by LasseRafn** [comment]
Sorry for the late response. Yeah I agree, have run into the same. I'm worried about just stripping null values though, as I am not certain all fields cannot be null? Their documentation is slightly vague about that, since they DO have a filter that allows for checking null values:

> Using null values in your filter
> Should you want to filter for the non existence of a property (i.e. null value) you can use the null escape sequence.
> $null:

But later they say:

> Nulling
> We do not generally accept null as a value and a validation exception should be expected. To null a property you must exclude it from your JSON on the write operation

Which is also very vague. They say they generally don't accept it, but "to null a property" 😅

I'm thinking adding a property / setting which automatically strips nulls, which will be turned on by default in future versions.

**Comment by LasseRafn** [comment]
Released in version 2.4.0

https://github.com/LasseRafn/laravel-economic/releases/tag/2.4.0
